version: '3.7'
services:

  celery:
    build: .
    command: celery -A Avito worker -l info
    volumes:
      - .:/usr/src/Avito
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A Avito beat -l info
    volumes:
      - .:/usr/src/Avito
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/Avito
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=apple.123
      - POSTGRES_DB=avito

  redis:
    image: redis
    restart: always
    command: redis-server
    ports:
      - 6379:6379

volumes:
  postgres_data:
  redisdata: